name: makerun - Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install gtest
      run: sudo apt-get install libgtest-dev
    - name: make
      run: make -C Test_Implementation/ run
