name: makerun - Build Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install gtest
      run: sudo apt-get install libgtest-dev
    - name: make controller
      run:  make -C Test_Implementation/ con
    - name: make sensor
      run:  make -C Test_Implementation/ sen
